---
title: Explore pairwise country similarities for drawings
subtitle: 
author: Molly Lewis 
date: "`r Sys.Date()`"
output: 
  html_document:
    toc_float: true
---
  
******
******
  
```{r setup, include = F}
rm(list=ls())

# load packages
library(knitr)
library(rmarkdown)
library(langcog)
library(tidyverse)
library(stringr)
library(purrr)
library(corrr)
library(countrycode)
library(ggjoy)

opts_chunk$set(echo = T, message = F, warning = F, 
               error = F, tidy = F, cache = F, fig.height = 4)
```
Here we're just looking at one item: __tree__

Read in drawing pairwise-sims file. 
```{r}
ITEM <- "tree"
tree <- read_csv("../../data/keras_similarities/pairwise_country/tree_pairwise_sims.csv") %>%
    mutate(key_id_1 = as.character(key_id_1),
           key_id_2 = as.character(key_id_2))
```

Where are the NA's coming from?
```{r}
nas <- tree %>%
  filter(is.na(cosine)) %>%
  mutate(key_id_1 = as.factor(key_id_1),
         key_id_2 = as.factor(key_id_2),
         country_code_1 = as.factor(country_code_1),
         country_code_2 = as.factor(country_code_2)) %>%
  count(key_id_1) %>%
  arrange(-n) %>%
  filter(n > 10 )
```

There are 8 that are NAs 
```{r}
ex <- read_feather(paste0("../../data/raw_data/feathers/atleast_100/", ITEM, ".txt"))

m = ex %>% 
  #filter(key_id %in% nas$key_id_1) %>%
  filter(key_id == "4504308487815168") %>%
  ggplot(aes(x = x, y = -y, color = country, alpha = recognized)) +
  ggtitle(ITEM)+
  facet_wrap(~key_id) +
  geom_point() +
  geom_path(aes(group = stroke_num)) +
  theme_bw()
```

```{r}
tree_clean <- tree %>%
  filter(!is.na(cosine)) %>%
  filter(country_code_1 %in% tree_big$country_code_1 & country_code_2 %in%   tree_big$country_code_1)
```

```{r}
get_unique_relation_id <- function (x, y){
  pairs = c(x, y)
  ordered = order(pairs)
  paste0(pairs[ordered[1]], pairs[ordered[2]])
}

tree_means <- tree_clean %>%
  group_by(country_code_1, country_code_2) %>%
  summarize(mean_cosine = mean(cosine),
            sd = sd(cosine),
            norm_mean = mean_cosine/sd) %>%
  rowwise() %>%
  mutate(all_codes = get_unique_relation_id(country_code_1, country_code_2)) %>%
  group_by(all_codes)%>%
  slice(1) %>%
  ungroup()%>%
  mutate(country_name_1 = as.factor(countrycode(country_code_1, "iso2c","country.name")),
         country_name_2 = as.factor(countrycode(country_code_2, "iso2c","country.name")),
         country_names = paste0(country_name_1,"_", country_name_2),
         continent_name_1 = as.factor(countrycode(country_code_1, 'iso2c', 'continent')),
         continent_name_2 = as.factor(countrycode(country_code_2, 'iso2c', 'continent')),
         cont_order_1 = unclass(continent_name_1) %>% as.numeric,
         cont_order_2 = unclass(continent_name_2) %>% as.numeric) %>%
  select(-country_code_1, -country_code_2, -continent_name_1, -continent_name_2) %>%
  arrange(-mean_cosine)
```
