---
title: Language correlations for google words
subtitle: 
author: Molly Lewis 
date: "`r Sys.Date()`"
output: 
  html_document:
    number_sections: false
    theme: cerulean
    toc_float: true
    code_folding: hide
---
  
******
******

```{r setup, include = F}

# load packages
library(tidyverse) 
library(knitr)
library(rmarkdown)
library(langcog)
library(broom)

opts_chunk$set(echo = T, message = F, warning = F, 
               error = F, tidy = F,  cache = F, fig.height = 4)
```  

```{r}
#utility function
get_unique_pairs <- function(dat) data.frame(unique(t(apply(dat, 1, sort))))
```


Read in correlations
```{r}
pairwise_word_distance_cosines <- read_csv("/Volumes/wilbur_the_great/CONCEPTVIZ/word_distances/word_dists_by_language.csv", col_names = c("word1", "word2", "cos_dist", "lang"))

all_langs <- unique(pairwise_word_distance_cosines$lang)
```


### Language correlations overall
```{r}

lang_lang_pairs <- list(x = all_langs, y = all_langs) %>%
  cross_df() %>%
  get_unique_pairs() %>%
  as.data.frame() %>%
  rename(lang1 = X1, lang2 = X2)  %>%
  mutate_all(as.character) %>%
  filter(lang1 != lang2)


get_language_pairwise_correlations <- function(lang1, lang2, corr_dat){
    corr_dat %>%
      filter(lang %in% c(lang1, lang2)) %>%
      spread(lang, cos_dist) %>%
      do(tidy(cor.test(unlist(.[,3]), unlist(.[,4]), na.action = "na.exclude"))) %>%
      select(-method, -alternative) %>%
      mutate(lang1 = lang1,
             lang2 = lang2) %>%
      select(lang1, lang2, everything())
}
get_language_pairwise_correlations_safe <- possibly(get_language_pairwise_correlations, data.frame(NA, NA, NA, NA, NA, NA, NA, NA))

language_correlations <- map2_df(lang_lang_pairs$lang1, 
     lang_lang_pairs$lang2, 
     get_language_pairwise_correlations,
     pairwise_word_distance_cosines) 

```

Dendogram
```{r}
lang_corrs_wide <- language_correlations %>%
  select(lang1, lang2, estimate) %>%
  spread(lang1, estimate) 

all_corrs_mat_langs <- as.matrix(lang_corrs_wide[,-1])
rownames(all_corrs_mat_langs) <- lang_corrs_wide$lang2

dist_matrix <- dist(all_corrs_mat_langs)
lang_clusts <- hclust(dist_matrix)
ggdendro::ggdendrogram(lang_clusts)
```

### Language correlations by domain

```{r}
CATEGORY_NAMES <- read_csv("/Volumes/wilbur_the_great/CONCEPTVIZ/misc/google_categories_coded.csv")  %>%
  filter(critical == 1,
         category %in% c("F", "K", "A", "M")) %>% 
  select(google_category_name, category) 
```

#### Food
```{r}
food_words <- filter(CATEGORY_NAMES, category == "F") %>% 
  select(google_category_name) %>% 
  unlist(use.names = F)
food_cosines <- pairwise_word_distance_cosines %>%
  filter(word1 %in% food_words,
         word2 %in% food_words)

language_correlations_wide_f <- map2_df(lang_lang_pairs$lang1, 
     lang_lang_pairs$lang2, 
     get_language_pairwise_correlations_safe,
     food_cosines) %>%
  select(lang1, lang2, estimate) %>%
  spread(lang1, estimate)  %>%
  filter(!is.na(lang2))

all_corrs_mat_langsf <- as.matrix(language_correlations_wide_f[,-1])
rownames(all_corrs_mat_langsf) <- language_correlations_wide_f$lang2
ggdendro::ggdendrogram(hclust(dist(all_corrs_mat_langsf)))
```

####  Artifact
```{r}
artifact_words <- filter(CATEGORY_NAMES, category == "A") %>% 
  select(google_category_name) %>% 
  unlist(use.names = F)
artifact_cosines <- pairwise_word_distance_cosines %>%
  filter(word1 %in% artifact_words,
         word2 %in% artifact_words)

language_correlations_wide_a <- map2_df(lang_lang_pairs$lang1, 
     lang_lang_pairs$lang2, 
     get_language_pairwise_correlations_safe,
     artifact_cosines) %>%
  select(lang1, lang2, estimate) %>%
  spread(lang1, estimate)  %>%
  filter(!is.na(lang2))

all_corrs_mat_langsa <- as.matrix(language_correlations_wide_a[,-1])
rownames(all_corrs_mat_langsa) <- language_correlations_wide_a$lang2
ggdendro::ggdendrogram(hclust(dist(all_corrs_mat_langsa)))
```


####  Buildings/Places
```{r}
building_words <- filter(CATEGORY_NAMES, category == "K") %>% 
  select(google_category_name) %>% 
  unlist(use.names = F)
building_cosines <- pairwise_word_distance_cosines %>%
  filter(word1 %in% building_words,
         word2 %in% building_words)

language_correlations_wide_b <- map2_df(lang_lang_pairs$lang1, 
     lang_lang_pairs$lang2, 
     get_language_pairwise_correlations_safe,
     building_cosines) %>%
  select(lang1, lang2, estimate) %>%
  spread(lang1, estimate)  %>%
  filter(!is.na(lang2))

all_corrs_mat_langsb <- as.matrix(language_correlations_wide_b[,-1])
rownames(all_corrs_mat_langsb) <- language_correlations_wide_b$lang2
ggdendro::ggdendrogram(hclust(dist(all_corrs_mat_langsb))) 
```

####  Weather
```{r}
weather_words <- filter(CATEGORY_NAMES, category == "M") %>% 
  select(google_category_name) %>% 
  unlist(use.names = F)
weather_cosines <- pairwise_word_distance_cosines %>%
  filter(word1 %in% weather_words,
         word2 %in% weather_words)

language_correlations_wide_w <- map2_df(lang_lang_pairs$lang1, 
     lang_lang_pairs$lang2, 
     get_language_pairwise_correlations_safe,
    weather_cosines) %>%
  select(lang1, lang2, estimate) %>%
  spread(lang1, estimate)  %>%
  filter(!is.na(lang2))

all_corrs_mat_langsw <- as.matrix(language_correlations_wide_w[,-1])
rownames(all_corrs_mat_langsw) <- language_correlations_wide_w$lang2
ggdendro::ggdendrogram(hclust(dist(all_corrs_mat_langsw))) 
```

