---
title: Within country prototype
author: Molly Lewis 
date: "`r Sys.Date()`"
output: 
  html_document:
    toc_float: true
    code_folding: hide
---
  
******
******
  
```{r setup, include = F}
rm(list=ls())


# load packages
library(knitr)
library(rmarkdown)
library(tidyverse)
library(purrr)
library(feather)
library(forcats)
library(data.table)
library(country_code)

source("../R_scripts/helpers.R")

opts_chunk$set(echo = T, message = F, warning = F, 
               error = F, tidy = F, cache = T, fig.height = 4)
```

Read in HD data
```{r}

hd_this_path <- paste0("../../data/hausdorff_similarities/within_country_distances/bread/bread_within_country_pairs_", GOOD_COUNTRIES[i], ".csv")

GOOD_COUNTRIES <- c("US", "NZ")
wpairwise_hds_raw <-  data.frame()
for (i in 1:length(GOOD_COUNTRIES)) {
    s <- read_csv( paste0("../../data/hausdorff_similarities/within_country_distances/bread/bread_within_country_pairs_", GOOD_COUNTRIES[i], ".csv"),  col_types = list(col_character(), col_character(), col_double(), col_character(), col_character()))
    wpairwise_hds_raw <- rbind(wpairwise_hds_raw, data.frame(s))
}
```

Get protoype
```{r}

prototypes <- wpairwise_hds_raw %>%
  group_by(country_code, key_id_1) %>%
  summarize(hd_sim = mean(hd_sim)) %>%
  arrange(hd_sim) %>%
  slice(1)

write_csv(prototypes, "../../data/hausdorff_similarities/within_country_distances/bread/key_id_protoype_country_key_bread.csv")
```


### Get jpegs for filtered sampled pairs
```{r }
# get all crit ids

nested_raw <- raw_data %>%
  filter(key_id %in% prototypes$key_id_1) %>%
  mutate(key_id_name = key_id) %>%
  group_by(key_id_name) %>%
  nest() 

# DO THE THING
JPEG_PATH <- paste0("../../data/hausdorff_similarities/pair_sim_drawings/images/", ITEM, "/")

walk(nested_raw$data, get_image_from_google_draw, 
                                      GDRAW_SIZE,
                                      IMAGENET_SIZE,
                                      N_INTERPOLATE, 
                                      return = "jpeg",
                                      jpeg_size = JPEG_SIZE,
                                      jpeg_path = JPEG_PATH)


```