---
title: Google Identified Analysis
subtitle: Do items that google identified how lower movers distance than those that do not?
author: Molly Lewis 
date: "`r Sys.Date()`"
output: 
  html_document:
    number_sections: false
    theme: cerulean
    toc_float: true
    code_folding: hide
---
  
******
******

```{r setup, include = F}
rm(list=ls())

# load packages
library(tidyverse) 
library(knitr)
library(rmarkdown)


opts_chunk$set(echo = T, message = F, warning = F, 
               error = F, tidy = F,  cache = F, fig.height = 4)

get_movers_dist_mat <- function(data.frame, all.combos) {
    word.list = unique(data.frame$word)
    my.list <- list()
    for (i in 1:length(word.list)){
      df <- data.frame %>%
        filter(word == word.list[i])%>%
        right_join(all.combos, by=c("country1", "country2"))%>%
        select(-word, -conc.bin)
    
      mat <-  spread(df, country1, dist) %>%
       as.data.frame() %>%
       remove_rownames() %>%
       column_to_rownames(var = "country2") %>%
       as.matrix()
      
       my.list[[i]] <- mat
    }
    my.list
}
```  

# Read in and bind all files
```{r}
file.list =  list.files("../../data/rdata/")

for (i in 1:length(file.list)){
    print(file.list[i])
    load(paste0("../../data/rdata/", file.list[i]))
    
    if(!exists("D")) {
      D <- d
    } else {
      D <- bind_rows(D, d)
    }
}


```
